name: Setup Bun
description: Download, install, and setup Bun to your path.
author: robobun
branding:
  icon: play-circle
  color: white
inputs:
  bun-version:
    description: 'The version of Bun to install. (e.g. "latest", "canary", "1.0.0", "1.0.x", <sha>)'
    required: false
  bun-version-file:
    description: 'The version of Bun to install from file. (e.g. "package.json", ".bun-version", ".tool-versions")'
    default: ".bun-version"
    required: false
  bun-download-url:
    description: "Override the URL to download Bun from. This skips version resolution and verifying AVX2 support."
    required: false
  registry-url:
    required: false
    description: "The URL of the package registry to use for installing Bun. Set the $BUN_AUTH_TOKEN environment variable to authenticate with the registry."
  scope:
    required: false
    description: "The scope for authenticating with the package registry."
  no-cache:
    required: false
    type: boolean
    default: false
    description: "Disable caching of bun executable."
outputs:
  bun-version:
    description: The version of Bun that was installed.
  bun-revision:
    description: The revision of Bun that was installed.
  bun-path:
    description: The path to the Bun executable.
  bun-download-url:
    description: The URL from which Bun was downloaded.
  cache-hit:
    description: If the version of Bun was cached.

runs:
  using: "node20"
  main: "dist/setup/index.js"
  post: "dist/cache-save/index.js"
  post-if: success()
