name: Setup Bun
description: Download, install, and setup Bun to your path.
author: robobun
branding:
  icon: play-circle
  color: white
inputs:
  bun-version:
    description: 'The version of Bun to install. (e.g. "latest", "canary", "1.0.0", "1.0.x", <sha>)'
    default: latest
    required: false
  registry-url:
    required: false
    description: "The URL of the package registry to use for installing Bun. Set the $BUN_AUTH_TOKEN environment variable to authenticate with the registry."
  scope:
    required: false
    description: "The scope for authenticating with the package registry."
outputs:
  bun-version:
    description: The version of Bun that was installed.
  bun-revision:
    description: The revision of Bun that was installed.
  cache-hit:
    description: If the version of Bun was cached.
runs:
  using: node20
  main: dist/index.js
