name: Setup Bun
description: Download, install, and setup Bun to your path.
author: robobun
branding:
  icon: play-circle
  color: white
inputs:
  bun-version:
    description: 'The version of Bun to install. (e.g. "latest", "canary", "0.5.6", <sha>)'
    default: latest
    required: false
outputs:
  bun-version:
    description: The version of Bun that was installed.
  cache-hit:
    description: If the version of Bun was cached.
runs:
  using: node16
  main: target/index.js
