name: Setup Bun with env BUN_VERSION
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  setup-bun:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        bun-version:
          - "0.5.6"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-bun
        name: Setup Bun
        uses: ./
        env:
          BUN_VERSION: ${{ matrix.bun-version }}
      - id: verify-bun
        name: Verify Bun
        run: |
          bun --version
