name: 🚀 Release new action version

on:
  release:
    types: [released]

  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: Tag name that the major tag will point to
        required: true

permissions:
  contents: write

jobs:
  update_tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/publish-action@23f4c6f12633a2da8f44938b71fde9afec138fb4 # v0.4.0
        env:
          TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
        with:
          source-tag: ${{ env.TAG_NAME }}
