name: 🧪 Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  remove-cache:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🗑️ Remove cache
        run: gh cache delete --all || true
        env:
          GH_TOKEN: ${{ github.token }}

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Bun
        uses: ./
        with:
          no-cache: true

      - name: Install dependencies
        run: |
          mkdir -p dist
          bun run bun_as:npm
          bun run bun_as:npx
          echo "$(realpath -e dist)" >> "${GITHUB_PATH}"
          PATH="${PATH}:$(realpath -e dist)"
          test -s bun.lock || bun run 'modules:lock'
          bun install --frozen-lockfile

      - name: Run tests
        run: bun test --coverage

  setup-bun:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    needs: [remove-cache, tests]

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - windows-11-arm
        bun-version:
          - latest
          - canary
          - "1.1.0"
          - "1.3.10"
          - "1.x"
          - "1"
          - "> 1.0.0"
          - "< 2"
          # https://github.com/oven-sh/setup-bun/issues/37
          # - "1.x"
          # - "1"
          # - "> 1.0.0"
          # - "< 2"
          # Disable <sha> support for now. This is because Github Artifacts
          # expire after 90 days, and we don't have another source of truth yet.
          # - "822a00c4d508b54f650933a73ca5f4a3af9a7983" # 1.0.0 commit

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🛠️ Setup Bun
        uses: ./
        id: setup_bun
        with:
          bun-version: ${{ matrix.bun-version }}
          no-cache: true

      - name: ▶️ Run Bun
        id: run_bun
        run: |
          bun --version

      - name: ⚖️ Verify Bun version
        uses: ./.github/actions/compare-bun-version
        with:
          bun-version: ${{ matrix.bun-version }}

  setup-bun-from-file:
    name: setup-bun from (${{ matrix.os }}, ${{ matrix.file.name }})
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    needs: [remove-cache, tests]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - windows-11-arm

        file:
          - name: package.json (packageManager bun@1.1.0)
            file: package.json
            run: |
              echo "$(jq '. += {"packageManager": "bun@1.1.0"}' package.json)" > package.json

          - name: foo/package.json (packageManager bun@1.1.0)
            file: foo/package.json
            run: |
              mkdir -p foo
              echo "$(jq '. += {"packageManager": "bun@1.1.0"}' package.json)" > foo/package.json

          - name: package.json (packageManager yarn@bun@1.1.0)
            file: package.json
            run: |
              echo "$(jq '. += {"packageManager": "yarn@bun@1.1.0"}' package.json)" > package.json

          - name: package.json (engines bun@1.1.0)
            file: package.json
            run: |
              echo "$(jq '.engines = {"bun": "1.1.0"}' package.json)" > package.json

          - name: .tool-versions (bun 1.1.0)
            file: .tool-versions
            run: echo "bun 1.1.0" > .tool-versions

          - name: .tool-versions (bun1.1.0)
            file: .tool-versions
            run: echo "bun1.1.0" > .tool-versions

          - name: .tool-versions (bun  1.1.0)
            file: .tool-versions
            run: echo "bun 1.1.0" > .tool-versions

          - name: .bumrc (1.1.0)
            file: .bumrc
            run: echo "1.1.0" > .bumrc

          - name: .bun-version (1.1.0)
            file: .bun-version
            run: echo "1.1.0" > .bun-version

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 📄 Setup file
        run: ${{ matrix.file.run }}

      - name: 🛠️ Setup Bun
        uses: ./
        with:
          bun-version-file: ${{ matrix.file.file }}
          no-cache: true

      - name: ⚖️ Compare versions
        uses: ./.github/actions/compare-bun-version
        with:
          bun-version: "1.1.0"

  setup-bun-from-package-json-without-specified-field:
    name: setup-bun from (${{ matrix.os }}, ${{ matrix.file.name }}) without specified field
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    needs: [remove-cache, tests]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - windows-11-arm

        file:
          - name: package.json (packageManager bun@1.1.0)
            file: package.json
            run: |
              echo "$(jq '. += {"packageManager": "bun@1.1.0"}' package.json)" > package.json

          - name: package.json (packageManager yarn@bun@1.1.0)
            file: package.json
            run: |
              echo "$(jq '. += {"packageManager": "yarn@bun@1.1.0"}' package.json)" > package.json

          - name: package.json (engines bun@1.1.0)
            file: package.json
            run: |
              echo "$(jq '.engines = {"bun": "1.1.0"}' package.json)" > package.json

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 📄 Setup file
        run: ${{ matrix.file.run }}

      - name: 🛠️ Setup Bun
        uses: ./
        with:
          no-cache: true

      - name: ⚖️ Compare versions
        uses: ./.github/actions/compare-bun-version
        with:
          bun-version: "1.1.0"

  setup-bun-download-url:
    name: setup-bun from (${{ matrix.os }}, download url)
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    needs: [remove-cache, tests]

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Normalize runner details
        id: normalized
        shell: bash
        run: |
          runner_arch="$(case '${{ runner.arch }}' in
            (X64) printf x64 ;;
            (ARM64) printf aarch64 ;;
            (*) echo "Unsupported runner.arch: ${{ runner.arch }}" >&2; exit 1 ;;
          esac)"
          runner_os="$(case '${{ runner.os }}' in
            (macOS) printf darwin ;;
            (Linux) printf linux ;;
            (Windows) printf windows ;;
            (*) echo "Unsupported runner.os: ${{ runner.os }}" >&2; exit 1 ;;
          esac)"
          printf >> "${GITHUB_OUTPUT}" -- '%s=%s\n' \
            runner_arch "${runner_arch}" \
            runner_os "${runner_os}"

      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🛠️ Setup Bun
        uses: ./
        id: setup_bun
        with:
          bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-${{ steps.normalized.outputs.runner_os }}-${{ steps.normalized.outputs.runner_arch }}.zip"

      - name: ▶️ Run Bun
        id: run_bun
        run: |
          bun --version

  test-custom-registries:
    name: test installing deps from custom registries (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    needs: [remove-cache, tests]
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🛠️ Setup Bun
        uses: ./
        id: setup_bun
        with:
          registries: |
            https://registry.npmjs.org
            @types:https://registry.yarnpkg.com

      - name: 🔎 Display registry configurations
        run: cat -v bunfig.toml

      - name: ▶️ Install from default registry
        shell: bash
        run: |
          status=0
          output=$(bun add is-odd --verbose --force 2>&1) || status=$?

          if [ 0 -eq "${status}" ] && grep <<<"$output" -q "HTTP/1.1 GET https://registry.npmjs.org/is-odd"; then
            echo "Successfully installed from default registry"
          else
            echo "${output}"
            echo "Return code: ${status}"
            echo "Failed to install from default registry"
            exit 1
          fi

      - name: ▶️ Install from @types registry
        shell: bash
        run: |
          status=0
          output=$(bun add @types/bun --verbose --force 2>&1) || status=$?

          if [ 0 -eq "${status}" ] && grep <<<"$output" -q "HTTP/1.1 GET https://registry.yarnpkg.com/@types%2fbun"; then
            echo "Successfully installed from @types registry"
          else
            echo "${output}"
            echo "Return code: ${status}"
            echo "Failed to install from @types registry"
            exit 1
          fi
